#!/usr/bin/env node
// Picks one generator seed per campaign level so difficulty follows a smooth curve, and writes
// src/levels.js. Run after changing the generator or campaignConfig:  node scripts/curate.js
//
// For each level we generate CANDIDATES boards, score each with the backtracking-player model in
// difficulty.js, and keep the one closest to the target for that level.
const fs = require('fs');
const path = require('path');
const B = require('../src/engine.js');
const D = require('./difficulty.js');

const CANDIDATES = 48;
const CAP = 3000;

// Target score per level. 0 = readable at a glance; ~3 = one tempting dead end; 6+ = real planning.
// Each world starts a bit above where the previous one started and climbs; the first two levels of a
// world (new piece) and every fifth level are breathers, so a hard stretch is always followed by a win.
const WORLD_RANGE = [[2.5, 6], [3, 7.5], [3.5, 8.5], [4, 9.5], [5, 11], [6, 12.5]];
function target(n) {
  if (n <= 5) return 0;
  const w = Math.floor((n - 1) / B.LEVELS_PER_WORLD);
  const k = (n - 1) % B.LEVELS_PER_WORLD;
  const [lo, hi] = WORLD_RANGE[w];
  const from = w === 0 ? 5 : 0;
  let t = lo + ((hi - lo) * (k - from)) / (B.LEVELS_PER_WORLD - 1 - from);
  if (w > 0 && k < 2) t = lo - 1.5;
  else if (k % 5 === 4) t -= 2;
  return Math.max(n <= 5 ? 0 : 2, t);
}

const seeds = [];
const report = [];
for (let n = 1; n <= B.CAMPAIGN_SIZE; n++) {
  const t = target(n);
  let best = null;
  for (let s = 0; s < CANDIDATES; s++) {
    const sc = D.score(B.campaign(n, s), CAP);
    const dist = Math.abs(sc - t);
    if (!best || dist < best.dist - 1e-9) best = { s, sc, dist };
  }
  seeds.push(best.s);
  report.push({ n, mirrors: B.campaignMirrors(n), target: +t.toFixed(1), score: +best.sc.toFixed(1) });
  process.stdout.write(`\rlevel ${n}/${B.CAMPAIGN_SIZE}`);
}
process.stdout.write('\n');

const out = `// Generated by scripts/curate.js — one generator seed per campaign level, chosen for a smooth difficulty curve.
// Difficulty score per level (target → chosen): ${report.map((r) => r.score).join(' ')}
(function (root) {
  const seeds = ${JSON.stringify(seeds)};
  if (typeof module === 'object' && module.exports) module.exports = seeds;
  else root.BEAMLINE_SEEDS = seeds;
})(typeof self !== 'undefined' ? self : this);
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'levels.js'), out);
for (let w = 0; w < B.WORLDS.length; w++) {
  const rows = report.slice(w * 20, w * 20 + 20);
  console.log(`${B.WORLDS[w].padEnd(7)} K: ${rows.map((r) => r.mirrors).join('')}  score: ${rows.map((r) => r.score).join(' ')}`);
}
